# This is a basic workflow to help you get started with Actions

name: Format with Black

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
<<<<<<< HEAD
<<<<<<< HEAD
    branches: [main]
=======
    branches: [ main ]
  pull_request:
    branches: [ main ]
>>>>>>> 8305cf5 (GitHub Actions automatic linting)
=======
    branches: [main]
<<<<<<< HEAD
  pull_request:
    branches: [main]
>>>>>>> bccc2bc (automatically push changes)
=======
>>>>>>> 33ca075 (Don't run on PRs)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> a79b6e8 (Let black work on PRs)
        with:
          ref: ${{ github.head_ref }}

      # Runs the code through Black
      - uses: piotrpawlaczek/python-blacken@release/stable
        with:
<<<<<<< HEAD
<<<<<<< HEAD
          only-check: "no"
          line-length: "88"
          sanity-check: "safe"
<<<<<<< HEAD
=======
          only-check: "no"
>>>>>>> bccc2bc (automatically push changes)
=======
>>>>>>> d79cb94 (Fix default formatting)

      # Pushes changes made by Black
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatically format with Black
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======

      # Runs the code through Black
      - uses: piotrpawlaczek/python-blacken@release/stable
>>>>>>> 8305cf5 (GitHub Actions automatic linting)
=======
          only-check: 'no'
>>>>>>> db29347 (automatically fix)
=======
>>>>>>> bccc2bc (automatically push changes)
=======
          create_branch: true

>>>>>>> cf2b6c9 (Update black.yml)
=======
>>>>>>> 33ca075 (Don't run on PRs)
